Problem statement

Dota2 is a free-to-play multiplayer online battle arena (MOBA) video game. Dota 2 is played in matches between two teams of five players, with each team occupying and defending their own separate base on the map. Each of the ten players independentlycontrols a powerful character, known as a "hero" (which they choose at the start of the match), who all have unique abilities and differing styles of play. During a match, players collect experience points and items for their heroes to successful battle with the opposing team's heroes, who attempt to do the same to them. A team wins by being the first to destroy a large structure located in the opposing team's base, called the "Ancient".

You’re given dataset of professional Dota players and their most frequent 10 heroes. The data also includes details about the heros (Kind of Hero (nuker, initiator and so on), their base attack, strength, movement speed). Here both train and test dataset is divided into two dataset(train9.csv & train1.csv and test9.csv & test1.csv).

train9.csv and train1.csv contain the user performance for their most frequent 9 heroes and 10th hero respectively. Both train9.csv and train1.csv have below fields.

test9.csv contain the different set of user (different from training set) performance for their most frequent 9 heroes. test9.csv has similar fields as train9.csv. Now, the aim is to predict the performance (kda_ratio) of the same set of users (test users) with the 10th hero which is test1.csv.

Import libraries

In [ ]:
import pandas as pd
import numpy as np

Read files

In [ ]:
#Load datasets
train9=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/train9.csv")
train9

user_id  hero_id        id  num_games  num_wins    kda_ratio
0            1       74      1_74        304       185  3743.699732
1            1       65      1_65        255       151  4009.021513
2            1       39      1_39        203       135  5094.621514
3            1      106     1_106        158       106  4619.212963
4            1        2       1_2        157        94  2871.627907
...        ...      ...       ...        ...       ...          ...
18841     2992        8    2992_8         97        59  4153.992395
18842     2992       34   2992_34         93        40  3571.428572
18843     2992       70   2992_70         89        53  4212.180747
18844     2992       76   2992_76        290       211  5471.003135
18845     2992      114  2992_114         89        58  4396.396396

[18846 rows x 6 columns]

In [ ]:
train1=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/train1.csv")
train1

user_id  hero_id       id  num_games  num_wins    kda_ratio
0           1       41     1_41        201       125  3731.707317
1           2       17     2_17        427       234  2922.058381
2           5      106    5_106        240       130  5116.682739
3           6       65     6_65        206       122  4131.553861
4           7       69     7_69        697       382  2474.469306
...       ...      ...      ...        ...       ...          ...
2089     2986       76  2986_76         21        14  4250.000000
2090     2989       27  2989_27         28        20  2368.888889
2091     2990        9   2990_9        260       132  3540.922619
2092     2991       33  2991_33        171       118  3933.422104
2093     2992       98  2992_98        135        78  3351.153040

[2094 rows x 6 columns]

In [ ]:
test9=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/test9.csv")
test9

user_id  hero_id        id  num_games  num_wins    kda_ratio
0           3       65      3_65        330       183  3418.470419
1           3      104     3_104        231       107  2522.639069
2           3        7       3_7        200       103  2793.255132
3           3       19      3_19        189        91  3493.495230
4           3        4       3_4        182       102  3586.402266
...       ...      ...       ...        ...       ...          ...
8077     2988       59   2988_59        152        95  2249.566724
8078     2988       34   2988_34        150        68  2807.453416
8079     2988       70   2988_70        149        70  2648.760331
8080     2988       34   2988_34         75        49  4036.402570
8081     2988      107  2988_107         71        44  2714.968153

[8082 rows x 6 columns]

In [ ]:
test1=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/test1.csv")
test1

user_id  hero_id       id  num_games
0          3       53     3_53        278
1          4       17     4_17        180
2          9       51     9_51         70
3         10       54    10_54        189
4         15       74    15_74        263
..       ...      ...      ...        ...
893     2981       16  2981_16         88
894     2983       46  2983_46        492
895     2985        2   2985_2        173
896     2987        7   2987_7        113
897     2988       11  2988_11        206

[898 rows x 4 columns]

In [ ]:
sample=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/sample.csv")
sample

id  kda_ratio
0       3_53          0
1       4_17          0
2       9_51          0
3      10_54          0
4      15_74          0
..       ...        ...
893  2981_16          0
894  2983_46          0
895   2985_2          0
896   2987_7          0
897  2988_11          0

[898 rows x 2 columns]

In [ ]:
heros=pd.read_csv("https://raw.githubusercontent.com/TracyRenee61/Felicity-Kings-of-ML/main/hero_data.csv")
heros

hero_id primary_attr attack_type  ... attack_rate  move_speed  turn_rate
0          1          agi       Melee  ...        1.45         310        0.5
1          2          str       Melee  ...        1.70         290        0.6
2          3          int      Ranged  ...        1.70         310        0.6
3          4          agi       Melee  ...        1.70         285        0.5
4          5          int      Ranged  ...        1.70         275        0.5
..       ...          ...         ...  ...         ...         ...        ...
110      112          int      Ranged  ...        1.70         285        0.5
111      113          agi      Ranged  ...        1.70         280        0.6
112      114          agi       Melee  ...        1.70         300        0.6
113      119          int      Ranged  ...        1.30         295        0.7
114      120          agi       Melee  ...        1.70         305        1.0

[115 rows x 23 columns]

Merge datasets

In [ ]:
train = pd.concat([train9, train1, test9])
train

user_id  hero_id        id  num_games  num_wins    kda_ratio
0           1       74      1_74        304       185  3743.699732
1           1       65      1_65        255       151  4009.021513
2           1       39      1_39        203       135  5094.621514
3           1      106     1_106        158       106  4619.212963
4           1        2       1_2        157        94  2871.627907
...       ...      ...       ...        ...       ...          ...
8077     2988       59   2988_59        152        95  2249.566724
8078     2988       34   2988_34        150        68  2807.453416
8079     2988       70   2988_70        149        70  2648.760331
8080     2988       34   2988_34         75        49  4036.402570
8081     2988      107  2988_107         71        44  2714.968153

[29022 rows x 6 columns]

Check for null values

In [ ]:
train.isnull().sum()

user_id      0
hero_id      0
id           0
num_games    0
num_wins     0
kda_ratio    0
dtype: int64

In [ ]:
test1.isnull().sum()

user_id      0
hero_id      0
id           0
num_games    0
dtype: int64

Define X and y values

In [ ]:
id = test1.id 

y = train[['num_wins', 'kda_ratio']]
X = train.drop(['id', 'num_wins', 'kda_ratio'], axis=1)
X_test = test1.drop(['id'],axis=1)

Create column transformer

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.datasets import fetch_openml
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

numeric_features = ['user_id', 'hero_id', 'num_games']
numeric_transformer = Pipeline(steps=[('imputer', IterativeImputer(random_state=1)),
    ('scaler', StandardScaler())])

#categorical_features = ['Embarked', 'Sex', 'Pclass', 'Title']
#categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
#    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(transformers=[
        ('num', numeric_transformer, numeric_features),
        #('cat', categorical_transformer, categorical_features)
        ])

Split X for training and testing

In [ ]:
#split train set for testing
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.10, random_state=1)
X_train.shape, X_val.shape, y_train.shape, y_val.shape, X_test.shape

((26119, 3), (2903, 3), (26119, 2), (2903, 2), (898, 3))

Define model

In [ ]:
!pip install catboost

     |████████████████████████████████| 66.3MB 59kB/s 


In [ ]:
from sklearn.multioutput import MultiOutputRegressor
from catboost import CatBoostRegressor

model = MultiOutputRegressor(CatBoostRegressor(iterations=2000, depth=5, learning_rate=0.1, loss_function='RMSE')).fit(X_train, y_train)
print(model.score(X_train, y_train))

0:	learn: 110.6234074	total: 50.9ms	remaining: 1m 41s
1:	learn: 101.4467188	total: 55.1ms	remaining: 55.1s
2:	learn: 93.0115841	total: 59ms	remaining: 39.3s
3:	learn: 85.6666967	total: 62.8ms	remaining: 31.4s
4:	learn: 78.9506881	total: 66.6ms	remaining: 26.6s
5:	learn: 72.7906658	total: 71.5ms	remaining: 23.7s
6:	learn: 67.6077444	total: 75.5ms	remaining: 21.5s
7:	learn: 62.7029242	total: 79.3ms	remaining: 19.8s
8:	learn: 58.4215607	total: 83.2ms	remaining: 18.4s
9:	learn: 54.6812194	total: 87ms	remaining: 17.3s
10:	learn: 51.5626149	total: 90.9ms	remaining: 16.4s
11:	learn: 48.6408198	total: 94.8ms	remaining: 15.7s
12:	learn: 46.1100217	total: 98.5ms	remaining: 15.1s
13:	learn: 43.8805140	total: 102ms	remaining: 14.5s
14:	learn: 41.9481147	total: 106ms	remaining: 14.1s
15:	learn: 40.2273979	total: 110ms	remaining: 13.6s
16:	learn: 38.7660098	total: 114ms	remaining: 13.3s
17:	learn: 37.4728746	total: 118ms	remaining: 13s
18:	learn: 36.3749416	total: 121ms	remaining: 12.7s
19:	learn: 3

Predict on validation set

In [ ]:
y_pred = model.predict(X_val)
print(model.score(X_val, y_val))

0.4785691487368321


In [ ]:
y_pred

array([[ 138.11430026, 3909.05914913],
       [ 194.85301878, 3713.21718406],
       [  76.93149682, 3969.45576987],
       ...,
       [  76.47028249, 3064.79797575],
       [  78.54321376, 3569.82370792],
       [ 159.91199533, 3315.53615104]])

Predict on test set

In [ ]:
prediction = model.predict(X_test)
prediction

array([[ 151.87441848, 2958.85187378],
       [ 105.04212176, 3747.19563928],
       [  41.77051167, 2635.6824742 ],
       ...,
       [  90.48994922, 2713.97175276],
       [  61.71019491, 3089.57261564],
       [ 112.03907562, 3534.82983544]])

In [ ]:
num_wins = prediction[:,0]
num_wins = num_wins.astype(int)
num_wins

array([ 151,  105,   41,  105,  144,  239,   95,  112,   64,   84,   79,
         31,   52,   81,   81,  143,   31,  116,   92,   61,  131,  193,
        116,  204,  128,  121,   73,  193,   35,   74,   13,  136,   61,
        163,   12,  139,  109,   26,  174,  187,  194,   35,   55,  105,
        166,   74,  161,  122,   86,  165,   21,   55,  115,   57,  304,
        202,  171,  129,  239,   26,   90,  377,   27,   86,   34,  154,
         94,  132,   76,   39,   20,  692,  103,  148,   65,   58,   49,
        205,   81,  126,  262,  158,   85,  202,  163,   39,   49,   24,
        385,  127,   58,  190,  167,   33,   48,   22,  107,   53,  161,
         45,   37,    8,  122,   59,   62,  209,   89,   40,   98,   38,
         71,    3,   48,   82,   81,  256,   14,  421,  225,   39,   81,
        144,  121,  123,  155,  102,   48,   77,   57,   41,   35,   57,
         23,  109,  229,   90,   93,   40,  237,   68,   67,  250,  102,
         95,  250,   48,  104,   99,   60,   69,   

In [ ]:
kda_ratio = prediction[:,1]
kda_ratio

array([2958.85187378, 3747.19563928, 2635.6824742 , 4159.37469683,
       3776.23429473, 3493.17214781, 4665.23983704, 3642.527551  ,
       3473.5404385 , 3675.58791342, 2717.99031513, 4803.83968007,
       3118.31496958, 3753.57900371, 2113.87769543, 3627.32801939,
       2744.6833761 , 2544.65604964, 2542.02097436, 3671.78591043,
       3154.53537961, 3098.41899803, 2437.49419252, 2593.04357953,
       3165.60821602, 3608.16675302, 2738.39762918, 3898.85867357,
       4148.20524824, 3793.55635966, 2468.69354236, 2707.5688479 ,
       4223.54554348, 3827.55326238, 4644.48723672, 3322.18919125,
       4312.42776571, 3997.35731604, 3782.99605643, 3579.27094975,
       3349.44351316, 3269.3522211 , 3806.96554566, 2980.31580633,
       2528.70567239, 3032.40068842, 3479.55591267, 3458.49673007,
       3821.60744431, 4002.09625257, 2607.03873084, 3726.97681104,
       3169.67383815, 3104.56714385, 3709.29802121, 3754.25577707,
       3128.34365216, 4006.06092376, 3880.31181049, 4221.86483

Prepare submission

In [ ]:
# creating dataframe with required columns 
submission = pd.DataFrame({'id':id,'kda_ratio':kda_ratio })
# creating csv file from dataframe
submission.to_csv('submission.csv',index = False)
submission

id    kda_ratio
0       3_53  2958.851874
1       4_17  3747.195639
2       9_51  2635.682474
3      10_54  4159.374697
4      15_74  3776.234295
..       ...          ...
893  2981_16  3396.870984
894  2983_46  3695.779420
895   2985_2  2713.971753
896   2987_7  3089.572616
897  2988_11  3534.829835

[898 rows x 2 columns]